/* SNAP STATE NAMES VALUES */
#define SEND_POWERED_STATE 0
#define WAIT_FOR_UPDATE_STATE 1
#define PREOCESS_DEVICE_UPDATE_STATE 2
#define GET_GS1011_NETWORK_STATE  3
#define GET_WEBSITE_IP_ADDRESS_STATE 4
#define SET_MARS_AS_WEBSITE_STATE 5
#define SET_KEEP_ALIVE_STATE 6
#define HTTPOPEN_GET_CID_STATE 7
#define CONVERT_DEVICE_DATA_AND_SEND_STATE 8
#define GET_WEBSITE_RESPONSE_SEND_DEVICE_STATE 9

#define RESET_NETWORK_ACCESS_STATE 10
#define SET_FACTORY_RESET_STATE 11
#define RESET_GS1011_ADAPTOR_STATE 12
#define DISACSSOCIATE_WEB_ACCESS_STATE 13
#define SET_INITIAL_IPADDRESS_STATE 14
#define SET_WEB_MODE_TO_LIMITED_STATE 15
#define INIT_WEB_ACCESS_STATE 16
#define SET_DHCPSRVR_STATE 17
#define SET_PROVISIONING_STATE 18

/* SNAP STATE CONSTANTS */
#define NULL 0X00
#define STX 0X02
#define ETX 0x03
#define LF 0x0A
#define CR 0x0d
#define DLE 0X10
#define BFRSIZE 255
#define BFRSIZEX2 512


